const appname = "Shark Market";
const appversion = "Version 1.0.0";
const credits = "@Emilkaagni";
const email = "email";
const emailHint = "admin@emil.com";
const password = "Password";
const passwordHint = "********";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Emil";
const forgetPass = "Forget Password";
const login = "Log in";
const signup = "Sign up";
const createNewAccount = "or, create a new account";
const loginWith = "login with";
const privacyPolicy = "Privacy Policy";
const termsAndCond = "Terms and Conditions";
const alreadyHaveAccount = "Already have an account?";

